apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  labels:
    app: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: 157931892911.dkr.ecr.us-east-1.amazonaws.com/myreact-ecr:v${GITHUB_RUN_NUMBER}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # Should match the port your React app is running on
