name: Build and push to Ecr

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Kubectl
        uses: azure/setup-kubectl@v2.0

      - name: Configure  Amazon Ecr
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Login To Amazon Ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: "latest" # Or specify a specific version of Helm

      - name: Generate Tag
        id: generate_tag
        run: echo "::set-output name=IMAGE_TAG::v${GITHUB_RUN_NUMBER}"

      - name: Update Kubernetest deployment
        run: |
          sed -i "s|image: 157931892911.dkr.ecr.us-east-1.amazonaws.com/myreact-ecr:v1|image: 157931892911.dkr.ecr.us-east-1.amazonaws.com/myreact-ecr:$IMAGE_TAG|g" Kubernetes/deploy.yml

      - name: Build & Tag Docker Image
        run: |
          docker build -t react-app-ecr:v${GITHUB_RUN_NUMBER} .
          docker tag react-app-ecr:v${GITHUB_RUN_NUMBER} 157931892911.dkr.ecr.us-east-1.amazonaws.com/myreact-ecr:v${GITHUB_RUN_NUMBER}
      - name: Push Docker Image to ecr
        run: docker push 157931892911.dkr.ecr.us-east-1.amazonaws.com/myreact-ecr:v${GITHUB_RUN_NUMBER}

      - name: Update Kube Config
        run: aws eks --region us-east-1 update-kubeconfig --name cluster-react

      - name: Deploy To Eks
        run: kubectl apply -f Kubernetes/deploy.yml -f Kubernetes/service.yml
