name: Build and push to Ecr

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Kubectl
        uses: azure/setup-kubectl@v2.0

      - name: Configure  Amazon Ecr
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Login To Amazon Ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Tag Docker Image
        env:
          ECR_REPO: 520062632936.dkr.ecr.us-east-1.amazonaws.com/react-ecr
          IMAGE_TAG: v${GITHUB_RUN_NUMBER}
        run: |
          docker build -t react-app-ecr:$IMAGE_TAG .
          docker tag react-app-ecr:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG

      
      - name: Push Docker Image to ecr
        run: docker push $ECR_REPO:$IMAGE_TAG

      - name: Update Kube Config
        run: aws eks --region us-east-1 update-kubeconfig --name cluster-react

      - name: Update Kubernetest deployment
        run: |
          sed -i.bak "s|$ECR_REPO:v1|$ECR_REPO:$IMAGE_TAG|g" Kubernetes/deploy.yml
          cat  Kubernetes/deploy.yml

      - name: Deploy To Eks
        run: kubectl apply -f Kubernetes/deploy.yml -f Kubernetes/service.yml
